// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RuteoBusesDAL;

#nullable disable

namespace RuteoBusesDAL.Migrations
{
    [DbContext(typeof(RuteoBusesDbcontext))]
    [Migration("20220820183550_initial")]
    partial class initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("RuteoBusesDAL.Bus", b =>
                {
                    b.Property<int>("busId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("busId"), 1L, 1);

                    b.Property<int>("choferId")
                        .HasColumnType("int");

                    b.Property<int>("estadoId")
                        .HasColumnType("int");

                    b.Property<int>("rutaAsignadaId")
                        .HasColumnType("int");

                    b.HasKey("busId");

                    b.HasIndex("choferId");

                    b.HasIndex("estadoId");

                    b.HasIndex("rutaAsignadaId");

                    b.ToTable("buses");
                });

            modelBuilder.Entity("RuteoBusesDAL.Chofer", b =>
                {
                    b.Property<int>("choferId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("choferId"), 1L, 1);

                    b.Property<string>("cedula")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("choferId");

                    b.ToTable("choferes");
                });

            modelBuilder.Entity("RuteoBusesDAL.Estado", b =>
                {
                    b.Property<int>("EstadoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EstadoId"), 1L, 1);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("EstadoId");

                    b.ToTable("estados");
                });

            modelBuilder.Entity("RuteoBusesDAL.ParadaRuta", b =>
                {
                    b.Property<int>("paradaRutaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("paradaRutaId"), 1L, 1);

                    b.Property<string>("nombreParadaRuta")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("rutaId")
                        .HasColumnType("int");

                    b.HasKey("paradaRutaId");

                    b.HasIndex("rutaId");

                    b.ToTable("paradarutas");
                });

            modelBuilder.Entity("RuteoBusesDAL.ParadaRutaAsignada", b =>
                {
                    b.Property<int>("paradaRutaAsignadaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("paradaRutaAsignadaId"), 1L, 1);

                    b.Property<string>("nombreParadaRutaAsignada")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("rutaAsignadaId")
                        .HasColumnType("int");

                    b.HasKey("paradaRutaAsignadaId");

                    b.HasIndex("rutaAsignadaId");

                    b.ToTable("paradaRutasAsignadas");
                });

            modelBuilder.Entity("RuteoBusesDAL.Ruta", b =>
                {
                    b.Property<int>("rutaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("rutaId"), 1L, 1);

                    b.Property<string>("nombreRuta")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("rutaId");

                    b.ToTable("rutas");
                });

            modelBuilder.Entity("RuteoBusesDAL.RutaAsignada", b =>
                {
                    b.Property<int>("rutaAsignadaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("rutaAsignadaId"), 1L, 1);

                    b.Property<double>("montoEstimado")
                        .HasColumnType("float");

                    b.Property<double>("montoRecibido")
                        .HasColumnType("float");

                    b.Property<int>("rutaId")
                        .HasColumnType("int");

                    b.HasKey("rutaAsignadaId");

                    b.HasIndex("rutaId");

                    b.ToTable("rutaAsignadas");
                });

            modelBuilder.Entity("RuteoBusesDAL.Bus", b =>
                {
                    b.HasOne("RuteoBusesDAL.Chofer", "chofer")
                        .WithMany("buses")
                        .HasForeignKey("choferId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RuteoBusesDAL.Estado", "estadoUnidad")
                        .WithMany("Buses")
                        .HasForeignKey("estadoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RuteoBusesDAL.RutaAsignada", "rutaAsignadaUnidad")
                        .WithMany("buses")
                        .HasForeignKey("rutaAsignadaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("chofer");

                    b.Navigation("estadoUnidad");

                    b.Navigation("rutaAsignadaUnidad");
                });

            modelBuilder.Entity("RuteoBusesDAL.ParadaRuta", b =>
                {
                    b.HasOne("RuteoBusesDAL.Ruta", "ruta")
                        .WithMany("paradas")
                        .HasForeignKey("rutaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ruta");
                });

            modelBuilder.Entity("RuteoBusesDAL.ParadaRutaAsignada", b =>
                {
                    b.HasOne("RuteoBusesDAL.RutaAsignada", "rutaAsignada")
                        .WithMany("paradas")
                        .HasForeignKey("rutaAsignadaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("rutaAsignada");
                });

            modelBuilder.Entity("RuteoBusesDAL.RutaAsignada", b =>
                {
                    b.HasOne("RuteoBusesDAL.Ruta", "ruta")
                        .WithMany()
                        .HasForeignKey("rutaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ruta");
                });

            modelBuilder.Entity("RuteoBusesDAL.Chofer", b =>
                {
                    b.Navigation("buses");
                });

            modelBuilder.Entity("RuteoBusesDAL.Estado", b =>
                {
                    b.Navigation("Buses");
                });

            modelBuilder.Entity("RuteoBusesDAL.Ruta", b =>
                {
                    b.Navigation("paradas");
                });

            modelBuilder.Entity("RuteoBusesDAL.RutaAsignada", b =>
                {
                    b.Navigation("buses");

                    b.Navigation("paradas");
                });
#pragma warning restore 612, 618
        }
    }
}
